[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "kso"
version = "0.1.0"
description = "A package for managing and training KSO object detection models (yolo for now) with MLflow ."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "av>=15.0",
    "boto3>=1.39",
    "ffmpeg-python>=0.2",
    "folium>=0.20",
    "ftfy>=6.3",
    "gdown>=5.2",
    "imageio>=2.37",
    "imageio-ffmpeg>=0.5",
    "imagesize>=1.4",
    "ipyfilechooser==0.6.0",
    "jupyter-bbox-widget==0.6.0",
    "jupyterlab==4.4.10",
    "jupyterlab-widgets==3.0.16",
    "matplotlib==3.10.8",
    "mlflow==3.7.0",
    "mlflow-export-import @ git+https://github.com/mlflow/mlflow-export-import.git@cf626079fc6729b10e34c2fd0fa3cf36fbfb30b2",
    "natsort>=8.3",
    "notebook==7.4.4",
    "numpy>=2.0",
    "opencv-python-headless==4.10.0.84",
    "pandas>=2.2",
    "panoptes-client==1.7.1",
    "pims>=0.7",
    "psutil>=7.0",
    "pyyaml>=6.0",
    "requests>=2.31",
    "setuptools<81",  # required by yolov5, but not defined in its dependencies
    "thop==0.1.1.post2209072238",
    "threadpoolctl==3.6.0",
    "tifffile==2025.12.12",
    "tiktoken==0.12.0",
    "tinycss2==1.4.0",
    "tokenize-rt==6.2.0",
    "tokenizers==0.22.2",
    "tomlkit==0.13.3",
    "torch>=2.9,<2.10",
    "torch-flops==0.4.1",
    "torch-summary==1.4.5",
    "torchinfo==1.8.0",
    "torchscan==0.1.1",
    "torchvision>=0.24,<0.25",
    "tornado==6.5.4",
    "tqdm==4.67.1",
    "traitlets==5.14.3",
    "typing-extensions==4.15.0",
    "typing-inspect==0.9.0",
    "typing-inspection==0.4.2",
    "tzdata==2025.3",
    "ultralytics==8.4.51",
    "ultralytics-thop==2.0.18",
    "wandb==0.21.0",
    "yolov5==7.0.14",
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[project.optional-dependencies]
dev = [
    "mypy-extensions==1.1.0",
    "nbqa==1.9.1",
    "pylint==3.3.8",
    "pytest==8.4.2",
]

[tool.uv.workspace]
members = [
    ".",
]

[tool.uv.sources]
kso2 = { workspace = true }
mlflow-export-import = { git = "https://github.com/mlflow/mlflow-export-import.git", rev = "cf626079fc6729b10e34c2fd0fa3cf36fbfb30b2" }
