[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "kso"
version = "0.1.0"
description = "A package for managing and training KSO object detection models (yolo for now) with MLflow ."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "av==15.0.0",
    "boto3==1.39.4",
    "ffmpeg-python==0.2.0",
    "folium==0.20.0",
    "ftfy==6.3.1",
    "gdown==5.2.0",
    "imageio==2.37.2",
    "imageio-ffmpeg",
    "imagesize==1.4.1",
    "ipyfilechooser==0.6.0",
    "jupyter-bbox-widget==0.6.0",
    "jupyterlab==4.4.10",
    "jupyterlab-widgets==3.0.16",
    "matplotlib==3.10.8",
    "mlflow==3.7.0",
    "mlflow-export-import @ git+https://github.com/mlflow/mlflow-export-import.git@cf626079fc6729b10e34c2fd0fa3cf36fbfb30b2",
    "natsort==8.4.0",
    "notebook==7.4.4",
    "numpy==2.2.6",
    "opencv-python-headless==4.10.0.84",
    "pandas==2.3.1",
    "panoptes-client==1.7.1",
    "pims==0.7",
    "psutil==7.1.3",
    "pyyaml==6.0.3",
    "requests==2.32.5",
    "setuptools==80.9.0",  # required by yolov5, but not defined in its dependencies
    "thop==0.1.1.post2209072238",
    "torch==2.8.0",
    "torchinfo==1.8.0",
    "torchvision==0.23.0",
    "tqdm==4.67.1",
    "ultralytics==8.3.166",
    "ultralytics-thop==2.0.18",
    "wandb==0.21.0",
    "yolov5==7.0.14",
]

[tool.pytest.ini_options]
testpaths = ["test"]

[project.optional-dependencies]
dev = [
    "mypy-extensions==1.1.0",
    "nbqa==1.9.1",
    "pylint==3.3.8",
    "pytest==8.4.2",
]

[tool.uv.workspace]
members = [
    ".",
]

[tool.uv.sources]
kso2 = { workspace = true }
mlflow-export-import = { git = "https://github.com/mlflow/mlflow-export-import.git", rev = "cf626079fc6729b10e34c2fd0fa3cf36fbfb30b2" }
