name: Increase docker space
description: Fix 'no space left on device' for docker

runs:
  using: "composite"
  steps:
    - name: Check disk space
      shell: bash
      run: |
        df -h

    # Currently (February 2026), github runners have 92G or 23G free space on /.
    # In the first case, no fixes are needed as there is enough space.
    # In the second case, the runner has /mnt mounted to some other volume with 66G free space.
    # Let's start by checking which kind of runner we got.
    - name: Check if /mnt is mounted
      id: mntcheck
      shell: bash
      run: |
        if grep -qE '[[:space:]]/mnt[[:space:]]' /proc/mounts; then
          echo "mounted=true" >> "$GITHUB_OUTPUT"
        else
          echo "mounted=false" >> "$GITHUB_OUTPUT"
        fi

    # If /mnt was mounted, then we don't likely have enough free space on /, so
    # we move the docker directory to /mnt to have enough space for building images.
    # This is much faster than erasing files to free disk space
    - name: Move docker directory
      if: steps.mntcheck.outputs.mounted == 'true'
      shell: bash
      run: |
        echo "---- Contents of /mnt -------------"
        ls /mnt
        echo "---- Info about /mnt --------------"
        cat /mnt/DATALOSS_WARNING_README.txt || true
        echo "-----------------------------------"
        sudo bash << EOF
        mv /var/lib/docker /mnt/
        mkdir /var/lib/docker
        mount --bind /mnt/docker /var/lib/docker
        EOF

    # This fix was last tested in November 2025.
    # If enabled later again, the list of removed paths might need to be updated.
    # We skip this erasing step to speed up the CI run.
    # If /mnt disappears at some point from the runner, you can gain disk space by enabling this.
    # See https://github.com/actions/runner-images/blob/0d358721aff04547ce591c7e1c444dc285fae993/images/ubuntu/Ubuntu2404-Readme.md
    - name: Free disk space with rm (specific to Ubuntu images)
      if: ${{ false }}
      shell: bash
      run: |
        sudo bash << EOF
        rm -rf "$ANDROID_SDK_ROOT"      # 12 GB
        rm -rf "$AGENT_TOOLSDIRECTORY"  #  6 GB
        rm -rf /usr/share/dotnet        #  4 GB
        rm -rf "$CONDA"                 #  1 GB
        EOF

    # This fix was last tested in November 2025.
    # If enabled later again, the list of removed packages might need to be updated.
    # We skip this erasing step to speed up the CI run.
    # If /mnt disappears at some point from the runner, you can gain disk space by enabling this.
    # See https://github.com/actions/runner-images/blob/0d358721aff04547ce591c7e1c444dc285fae993/images/ubuntu/Ubuntu2404-Readme.md
    - name: Free disk space with apt (specific to Ubuntu images)
      if: ${{ false }}
      shell: bash
      run: |
        sudo bash << EOF
        # Remove browsers
        apt-get remove --purge -y microsoft-edge-stable google-chrome-stable firefox
        # Remove java
        apt-get remove --purge -y '^temurin-*' '^openjdk-*'
        # Remove unnecessary tools
        apt-get remove --purge -y azure-cli '^google-cloud-*' powershell '^mysql-*' '^dotnet-.*'
        # Remove compilers
        apt-get remove --purge -y '^llvm-*' '^libllvm-*' '^gfortran-*' gcc-{9,10,11,12,13}
        # Clean
        apt-get autoremove -y
        apt-get clean && rm -rf /var/lib/apt/lists/*
        EOF
        # List remaining large packages
        dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -n 10

    - name: Check disk space
      shell: bash
      run: |
        df -h
