name: Build Docker Image
'on':
  push:
    branches:
      - master
      - dev
    paths:
      - Dockerfile
      - kso_utils/requirements
      - yolov5_tracker/requirements
      - yolov5/requirements
  pull_request: 
    branches:
      - master
      - dev
    #paths:
    #  - Dockerfile
    #  - kso_utils/requirements
    #  - yolov5_tracker/requirements
    #  - yolov5/requirements
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Build the Docker image
        uses: docker/build-push-action@v4
        with:
          load: true
          tags: test-image
          outputs: type=docker, dest=/tmp/myimage.tar
        #run: docker build . --file Dockerfile --tag
      - 
        name: Upload artifact
        uses: actions/upload-artifacts@v3
        with:
          name: test-image
          path: /tmp/test-image.tar
  