name: Build EDITO
on:
  push:
    branches:
      - "*"
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  plan:
    name: Plan build
    runs-on: ubuntu-latest
    outputs:
      build_platforms: ${{ steps.diff.outputs.build_platforms }}
      plan: ${{ steps.diff.outputs.plan }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Plan build
        id: diff
        env:
          GH_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          set -euo pipefail

          # Check whether workflow was triggered by a fork
          if [[ "${{ github.repository }}" == "ocean-data-factory-sweden/kso" ]]; then
            is_fork=false
          else
            is_fork=true
          fi

          # Check whether workflow was triggered by a push of a tag
          is_tag=${{ github.ref_type == 'tag' }}

          # Add 'latest" tag for versioned git tags
          is_latest=$is_tag

          # Platforms
          platforms=(cpu)

          # Names of the images
          base_tag=dev
          cache_tag_prefix=buildcache
          image_name=ghcr.io/${{ github.repository }}-edito        # ghcr.io/ocean-data-factory-sweden/kso-edito
          extra_caches=()
          if $is_tag; then
            build_tag=${{ github.ref_name }}; build_tag=${build_tag#v}  # 1.2.3-beta
            cache_tag=$cache_tag_prefix-$base_tag                       # buildcache-dev
          else
            build_tag=${{ github.ref_name }}                            # name
            cache_tag=$cache_tag_prefix-$build_tag                      # buildcache-name
            if [[ "$build_tag" != "$base_tag" ]]; then
              # Add dev branch as an extra cache for other branches
              extra_caches+=("$image_name:$cache_tag_prefix-$base_tag")
            fi
          fi

          # Add upstream repo as an extra cache for forks
          if $is_fork; then
            extra_caches+=("ghcr.io/ocean-data-factory-sweden/kso-edito:$cache_tag_prefix-$base_tag")
          fi

          # Find the commit sha of the latest successful workflow run.
          # The latest pushed image should correspond to this tag
          sha=$(gh api repos/${{ github.repository }}/actions/runs?branch=${{ github.ref_name }} --paginate \
            --jq '.workflow_runs | map(select(.name == "Build EDITO" and .conclusion == "success")) | first | .head_sha')

          # Check that this commit is part of the current branch
          # (might not be if the branch has been rebased).
          conditional_build=false
          if [[ "$sha" != "" ]]; then
            echo "Found commit with previous successful build: $sha"
            if git cat-file -e "$sha"^{commit} 2>/dev/null; then
              echo "This commit is valid -> Enabling conditional build"
              ref_sha=$sha
              conditional_build=true
            else
              echo "This commit is not valid (maybe rebased branch?) -> Building everything"
            fi
          fi

          if $conditional_build; then
            # Current commit sha
            head_sha=${{ github.sha }}

            # Compare
            echo -e "Diffing from $ref_sha to $head_sha"
            git diff --name-only "$ref_sha" "$head_sha" > changed.txt

            echo -e "\nChanged files:"
            cat changed.txt
          fi

          # Helper function for editing file inline with jq
          jq_inline() {
            local tmp=$(mktemp)
            jq "$@" > "$tmp"
            mv "$tmp" "${@: -1}"
          }

          # Initialize output jsons
          echo '[]' > build_platforms.json
          echo '{}' > plan.json

          # Loop over platforms
          ubuntu_version=24.04
          for platform in "${platforms[@]}"; do

            case "$platform" in
              cpu)
                cuda_version=false
                rocm_version=false
                platform_tag=ubuntu$ubuntu_version
                base_image=docker.io/inseefrlab/onyxia-jupyter-python:py3.12.12
                python_requirements=requirements_cpu.txt
                ;;

              cuda)
                cuda_version=12.9
                cuda_patch_version=1
                rocm_version=false
                test=false
                platform_tag=cuda$cuda_version-ubuntu$ubuntu_version
                base_image=nvcr.io/nvidia/cuda:$cuda_version.$cuda_patch_version-cudnn-runtime-ubuntu$ubuntu_version
                python_requirements=requirements_cuda${cuda_version}.txt
                ;;

              rocm)
                cuda_version=false
                rocm_version=6.4
                rocm_patch_version=4
                test=false
                platform_tag=rocm$rocm_version-ubuntu$ubuntu_version
                base_image=docker.io/rocm/dev-ubuntu-$ubuntu_version:$rocm_version.$rocm_patch_version
                python_requirements=requirements_rocm${rocm_version}.txt
                ;;
            esac

            # Check whether the image needs to be built
            image="$image_name:$build_tag-$platform_tag"
            if $conditional_build; then
              # Build image only if needed
              build_image=false
              # Build if this ci workflow has changed
              if grep -qF '.github/workflows/build-and-test.yml' changed.txt; then
                build_image=true
              fi
              # Build if container recipe has changed
              if grep -qE '^containers/edito/' changed.txt; then
                build_image=true
              fi
              # Build if python packages have changed
              if grep -qF 'requirements.txt' changed.txt; then
                build_image=true
              fi
              if grep -qF "$python_requirements" changed.txt; then
                build_image=true
              fi

              # Find existing image to be used if not building image
              if ! $build_image; then
                if ! docker manifest inspect "$image" > /dev/null 2>&1; then
                  # No existing image found; need to build a new image
                  build_image=true
                fi
              fi
            else
              # Build image always for dev and main
              build_image=true
            fi

            # Tags for the build
            image_tags="$image"

            # Add "latest" tag for cpu image
            if [[ "$is_latest" == "true" && "$platform" == "cpu" ]]; then
              image_tags="$image_tags"$'\n'"$image_name:latest"
            fi

            # Build caches
            image_cache_to="type=registry,ref=$image_name:$cache_tag-$platform_tag,mode=max"
            image_cache_from="type=registry,ref=$image_name:$cache_tag-$platform_tag"
            for cache in "${extra_caches[@]}"; do
              image_cache_from+=$'\n'"type=registry,ref=$cache-$platform_tag"
            done

            # Update platform lists
            if $build_image; then
              jq_inline --arg p $platform '.+[$p]' build_platforms.json
            fi

            # Update plan
            for k in \
              cuda_version \
              rocm_version \
              build_image \
              image \
              image_tags \
              base_image \
              image_cache_to \
              image_cache_from \
              python_requirements \
            ; do
              jq_inline --arg p $platform --arg k "$k" --arg v "${!k}" '.[$p][$k]=$v' plan.json
            done

          done

          # Print plans
          echo -e "\nBuild image for these platforms:"
          cat build_platforms.json
          echo -e "\nPlan:"
          cat plan.json

          # Emit json strings as a step output
          echo "build_platforms=$(jq -c . build_platforms.json)" >> "$GITHUB_OUTPUT"
          echo "plan=$(jq -c . plan.json)" >> "$GITHUB_OUTPUT"

  build-and-push:
    name: Build and push image
    needs: [plan]
    if: ${{ needs.plan.outputs.build_platforms != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        platform: ${{ fromJSON(needs.plan.outputs.build_platforms) }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6

      - name: Increase docker space
        uses: ./.github/actions/increase-docker-space

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: '${{ github.actor }}'
          password: '${{ secrets.GITHUB_TOKEN }}'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v6
        if: ${{ fromJSON(needs.plan.outputs.plan)[matrix.platform]['build_image'] == 'true' }}
        with:
          file: containers/edito/Dockerfile
          platforms: linux/amd64
          provenance: false   # Disable to avoid unknown/unknown; see https://github.com/orgs/community/discussions/45969
          sbom: false         # Disable to avoid unknown/unknown; see https://github.com/orgs/community/discussions/45969
          push: true
          tags: ${{ fromJSON(needs.plan.outputs.plan)[matrix.platform]['image_tags'] }}
          cache-to: ${{ fromJSON(needs.plan.outputs.plan)[matrix.platform]['image_cache_to'] }}
          cache-from: ${{ fromJSON(needs.plan.outputs.plan)[matrix.platform]['image_cache_from'] }}
          build-args: |
            BASE_IMAGE=${{ fromJSON(needs.plan.outputs.plan)[matrix.platform]['base_image'] }}
            PYTHON_REQUIREMENTS=${{ fromJSON(needs.plan.outputs.plan)[matrix.platform]['python_requirements'] }}
