name: Build Docker Image
'on':
  push:
    branches:
      - master
      - dev
    paths:
      - Dockerfile
      - kso_utils/requirements
      - yolov5_tracker/requirements
      - yolov5/requirements
  pull_request: 
    branches:
      - master
      - dev
    paths:
      - Dockerfile
      - kso_utils/requirements
      - yolov5_tracker/requirements
      - yolov5/requirements
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Free disk space (specific to Ubuntu images)
        run: |
          sudo rm -rf /usr/share/dotnet || true
          sudo rm -rf "$AGENT_TOOLSDIRECTORY" || true
      
