name: Code quality test 

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      uid_gid: ${{ steps.get-user.outputs.uid_gid }}
    steps:
      - id: get-user
        run: echo "::set-output name=uid_gid::$(id -u):$(id -g)"


  pytest:
    runs-on: ubuntu-latest
    needs: [configure]
    container:
      image: ghcr.io/${{ github.repository }}:dev
      options: --user ${{ needs.configure.outputs.uid_gid }}
      credentials:
        username: '${{ github.actor }}'
        password: '${{ secrets.GITHUB_TOKEN }}'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install pylint and analyse all .py and .ipynb files
        run: |
          python3 -m pip install pylint
          /github/home/.local/bin/pylint **/*.py
        # HACK: add pylint to requirements later, then we can just have pylint here instead of this path.