name: Code formatting

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master
      - dev
      - main

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          jupyter: true
          version: "~= 24.0"
