name: Code quality test 
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          echo $PATH
          echo readlink -f .
          python3 -m pip --no-cache-dir install --upgrade pip
          python3 -m pip --no-cache-dir install numpy 
          python3 -m pip --no-cache-dir install \
            -r kso/yolov5_tracker/requirements.txt \
            -r kso/yolov5_tracker/yolov5/requirements.txt \
            -r kso/kso_utils/requirements.txt
      - name: Install pylint
        run: python3 -m pip install pylint
      - name: Analyse all .py files with pylint
        run: pylint --errors-only --output-format=colorized **/*.py

