name: part2
on:
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - Dockerfile
      - kso_utils/requirements
      - yolov5_tracker/requirements
      - yolov5/requirements
  pull_request: 
    branches:
      - master
      - dev
    paths-ignore:
      - Dockerfile
      - kso_utils/requirements
      - yolov5_tracker/requirements
      - yolov5/requirements
  workflow_run:
    workflows: [part1]
    types: [completed]
jobs:
  part2:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: on workflow_run
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: echo 'triggering by workflow_run'
      - 
        name: on PR or push
        if: ${{ github.event.workflow_run.conclusion != 'success' }}
        run: echo 'triggering by PR or push'
      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: print sha
        run: echo ${{ github.sha }} 
      #-
        #name: Check docker exists, old
        #run: |
        #     curl --head --fail -H "Authorization: Bearer ${GHCR_TOKEN}" https://ghcr.io/${{ github.repository }}/manifest/ghcr.io/${{ github.repository }}:test5
      - name: Check docker exists Pablo
        run: |
          curl -H "Authorization: Bearer ${{secrets.GHCR_TOKEN}}" https://ghcr.io/v2/ocean-data-factory-sweden/kso/tags/list
             
             
             #curl -H "Authorization: Bearer ${secrets.GITHUB_TOKEN}" https://ghcr.io/${{ github.repository }}/tags/list  