name: Run tests without building a new docker file
on:
  push:
    branches:
      - master
      - dev
  pull_request: 
    branches:
      - master
      - dev

jobs:
  configure: # to get the gitlab runner id to be able to checkout the repository. otherwise you do not have permission
    runs-on: ubuntu-latest
    outputs:
      uid_gid: ${{ steps.get-user.outputs.uid_gid }}
    steps:
      - id: get-user
        run: echo "::set-output name=uid_gid::$(id -u):$(id -g)"

  test-notebooks:
    runs-on: ubuntu-latest
    needs: configure
    container:
      image: ghcr.io/${{ github.repository }}:PR
      options: --user ${{ needs.configure.outputs.uid_gid }}
      credentials:
        username: '${{ github.actor }}'
        password: '${{ secrets.GHCR_TOKEN }}'
    permissions:
      contents: read
      packages: write
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
      -
        name: show pip list
        run: pip list
      -
        name: Install pytest
        run: pip install pytest 
      - 
        name: pip show pytest
        run: pip show pytest
      - 
        name: Login W&B
        if: github.ref != 'refs/heads/master'
        shell: bash
        env:
          WANDB_API: ${{ secrets.WANDB_KEY }}
        run: wandb login "$WANDB_API"
      - 
        name: Run notebook tests
        if: github.ref != 'refs/heads/master'
        id: tests
        run: >-
          cp src/multi_tracker_zoo.py yolov5_tracker/trackers/multi_tracker_zoo.py && pytest --disable-warnings test/widget-tests.py && pytest --disable-warnings --zoo_user=${{ secrets.ZOO_USERNAME }}
          --zoo_pass=${{ secrets.ZOO_TOKEN }} test/notebook-tests.py 
  